//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorizontalList
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableView
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string ProductGroup { get; set; }
        public string Manufacturer { get; set; }
        public string SelfI { get; set; }
        public string Address { get; set; }
        public int Quantity { get; set; }
    }
}
